# Generated by Django 3.1.5 on 2021-06-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20210622_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='title',
        ),
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
