# Generated by Django 3.1.5 on 2021-06-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_auto_20210622_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='author',
        ),
    ]
