# Generated by Django 3.1.5 on 2021-06-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_remove_forum_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
