# Generated by Django 3.1.5 on 2021-06-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20210623_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum2',
            new_name='Forum',
        ),
    ]
