# Generated by Django 3.1.5 on 2021-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_auto_20210623_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='forum',
            name='content',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
