# Generated by Django 3.1.5 on 2021-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_auto_20210623_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
